[package]
name = "session-io"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
wordle-io.workspace = true
gstd.workspace = true
gmeta.workspace = true
parity-scale-codec.workspace = true
scale-info.workspace = true